### ISSUE TITLE
Replacing LowMC

### ISSUE THREAD

**Issue by codydresel** [Microsoft/Picnic#4]
What would it take to replace LowMC with say AES, SHA, etc?
Could you replace
`runMPC(views[k], &tape, plaintext, (uint32_t*)tmp, params); and it's implementation:
void mpc_LowMC(randomTape_t* tapes, view_t views[3],  const uint32_t* plaintext, uint32_t* slab, paramset_t* params)`
or is there other assumptions in the algorithm about LowMC being used?

**Comment by zaverucha** [comment]
(Sorry for the slow response, I've updated my notification settings.)

Replacing LowMC with another algorithm would be a large change, yes mainly in those functions you list and the corresponding verification functions. Many of the mpc_* functions could be re-used for SHA2, but you'd need, e.g., mpc_rotate, LowMC doesn't use rotations.  The ZKBoo SHA256 code would be helpful since it implements SHA-256 as an MPC (https://github.com/Sobuno/ZKBoo/).  Key generation would have to change too (in picnic.c), and serialization.

What are you trying to do?  Benchmark Picnic instantiations with other primitives? Hoist out the proof system for use in another application?

**Comment by codydresel** [comment]
Hello!
No worries,
Thank you very much for the information.

I'm interested in testing and benchmarking picnic instantiated with SHA2 instead of LowMC. 

Any advice, help, or code would be much appreciated.

**Comment by zaverucha** [comment]
One way to get something fairly close to Picnic would be to start with the ZKBoo implementation, then add the optimizations described in https://eprint.iacr.org/2017/279.  The signature size would be about 618KB (see page 6 of the paper) at the L1 security level (compared to about 32KB for Picnic-L1-FS).  If you use the new proof system described in the latest version of the spec, a really rough estimate for the SHA-256 proof size would be 200KB (again, at L1, and for comparison Picnic2-L1-FS signatures are about 12KB), but it would be more work to implement.

**Comment by zaverucha** [comment]
Actually, for a circuit as large as SHA-256, Ligero is probably the proof system that will have the shortest proofs.  The paper is here: https://acmccs.github.io/papers/p2087-amesA.pdf but I don't find the code anywhere online :(

**Comment by codydresel** [comment]
Thank you very much for the information and resources! It's much appreciated.
